//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.0
//     from Assets/Scripts/Input Settings/UIControlActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input Settings/UIControlActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @UIControlActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @UIControlActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIControlActions"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""147ec46a-df48-4a13-80ec-062dd1fd2a9a"",
            ""actions"": [
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""db5f52c4-8916-4ce3-87a6-857ee71d15a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseZoom"",
                    ""type"": ""Value"",
                    ""id"": ""e9e17534-899a-4903-a580-ba6de680a6fc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""ScaleVector2(x=120,y=120)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""b382e10c-648a-42fe-99e1-a383f08974a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSettings"",
                    ""type"": ""Button"",
                    ""id"": ""7edd42f4-6c3c-4eb4-9116-2311633dc938"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseWindow"",
                    ""type"": ""Button"",
                    ""id"": ""76194f25-8a56-457d-9cb8-796bf3ff4657"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DefenseBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""3125c5bb-bc84-43a0-9706-0a745b619b4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IndustryBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""cdc85c29-d927-4267-b262-fa85e92c8d2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""578996e3-90f0-4953-bfcc-f303c2894fbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PopulationBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""0ce1deb0-d2a3-4d7e-a21e-b0636b622c78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CorporateBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""636eb401-48f4-4231-b9fd-bbf6dbc35f66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TileMenu"",
                    ""type"": ""Button"",
                    ""id"": ""ccab643f-ec44-49a2-9cd9-42dd535d5ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUnit"",
                    ""type"": ""Button"",
                    ""id"": ""f68e5075-45be-4458-98af-c57922f4b9ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCheats"",
                    ""type"": ""Button"",
                    ""id"": ""53eb4c35-6205-4fa7-9903-fc0476f9688c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltPressed"",
                    ""type"": ""Button"",
                    ""id"": ""2dedd837-cc18-4270-b6f4-011f4d14f95a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""22e7730a-6504-45f6-b8c0-0bce3e270593"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NormalSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""14a0ace3-a0dd-45ea-ae91-d639feff17ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""6485f01b-6bc4-4623-84b8-f68c83c50d12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TripleSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""51a0fc16-712b-46b0-8c97-867af172ef53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TechTree"",
                    ""type"": ""Button"",
                    ""id"": ""7b844b46-9ec8-4c4e-a855-70385ccf7ce0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Market"",
                    ""type"": ""Button"",
                    ""id"": ""282d0550-8ec6-4c4f-afab-27e3281b9da2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoTrader"",
                    ""type"": ""Button"",
                    ""id"": ""b1b43f57-1ad1-4ace-98ce-677bd2953a95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HireMenu"",
                    ""type"": ""Button"",
                    ""id"": ""1b8a0534-e99e-400d-ab96-e45ad708d322"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feedback"",
                    ""type"": ""Button"",
                    ""id"": ""2419eab5-7e3a-4cc9-b2fa-4cc43db4b541"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceLasers"",
                    ""type"": ""Button"",
                    ""id"": ""3e229d39-650e-41b9-b704-ccfe8ab0bc8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group1"",
                    ""type"": ""Button"",
                    ""id"": ""8d605fe5-deb5-4c2b-a70e-ff3aedd3472c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group2"",
                    ""type"": ""Button"",
                    ""id"": ""dab28750-b076-486a-9c95-3e98b9974059"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group3"",
                    ""type"": ""Button"",
                    ""id"": ""b3beafcc-3fb3-4a4b-9197-e5eb501edf2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group4"",
                    ""type"": ""Button"",
                    ""id"": ""c4cec9a8-b1e9-4abf-8555-debb450be2a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group5"",
                    ""type"": ""Button"",
                    ""id"": ""8893827d-1123-496e-93ea-ea272e57cf0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabGroup"",
                    ""type"": ""Button"",
                    ""id"": ""a714751c-9039-480f-b640-ea74a83b89e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenLoad"",
                    ""type"": ""Button"",
                    ""id"": ""b62a20f3-e223-426d-8d77-94a6ad1f20fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSave"",
                    ""type"": ""Button"",
                    ""id"": ""fad4a706-5b7a-4e7e-8a74-ff26f7c2f5ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""53b4fd35-51d3-499c-8692-7a52d046a359"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DefenseBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""134cac0a-29b4-4522-821c-abdd5197dc94"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IndustryBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""105cca7a-5e03-4c9f-934e-78366b55e034"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc08b468-97ea-4927-ac37-c97967da86c7"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PopulationBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e24a7c01-e1d9-46c8-85c3-498248347c22"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CorporateBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56d8ea2-5e6a-454e-8016-4dc0048b28fb"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TileMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0377cc2e-1a4d-4763-a7d6-7eadaf5b0185"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f127b8d1-3290-4a27-a091-9b38e2091b7c"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=120,y=120)"",
                    ""groups"": """",
                    ""action"": ""MouseZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90b887c7-cb7b-4786-94f9-8868292f26fa"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b6c1d5e-1cc3-49f7-9907-9cf5f995d4a5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1992e84-3ad4-4b33-924b-0c3d5f457f3f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e66a906c-8f47-44bf-9b42-299558ba7a29"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""a2f02bd5-2778-42da-910c-6d4c2355e67a"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""ab91c920-b077-4ddd-8bfc-ff31a7405431"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ffb0e9bb-dce4-4e9d-ae07-1b071636c7b8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5b508e99-e484-466e-a1dd-2e0e3b1b19d5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""33528b52-458d-4946-aa57-c45b5b1fc0b6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04f45881-02c1-4474-8b48-4e4fa018a9e0"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""678b61cc-1961-41c6-a229-3fd90ea84382"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b48837ac-92c5-4918-8ed9-b7dd9764f271"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0fcf5e1-4c23-4557-a547-71015ca3dd01"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoubleSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f38ec7ed-6964-4218-a289-99218f5d9d2f"",
                    ""path"": ""<Keyboard>/backslash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TripleSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44d9cdb1-de87-44d1-8c46-5c0f3e595fe0"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TechTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b08cce15-d8ce-48c2-ae2f-855d1d762b57"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Market"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99dfdcb8-06ed-48e5-a882-8f10b153fba4"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HireMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""728fe859-ade9-4644-a348-60daf48c0185"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feedback"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4271eb22-e06c-4a35-a897-53875827403d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceLasers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f26fbdf7-fc00-4c94-9777-13660a4b8f95"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ac0e9a6-44bd-4f80-90a6-cabdfa3ba33a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47506cb8-d18d-4ddf-8afb-1617872fe8d3"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34fa6486-b556-4a56-b2ff-56b9a858f30f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fab71d4f-9594-4be4-8c26-1f80f6d740c6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e7c8fcf-2cf0-4a70-ad32-4fb338d6bf6e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c5fdc7da-13ff-4a8f-8d6f-733033ec4709"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLoad"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""aef710f5-9c3f-41b4-ad33-6e03e143c941"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6a90f581-3276-4e3d-84a1-d7857d881c79"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""94005153-8679-4b35-8ad9-3f5dcb01ad2b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSave"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a6b4d134-dc84-4e75-960b-00fffd264740"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""74f0a558-4b67-4b10-8649-8258bfbde699"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""babc4fb5-51d2-4ded-8e86-599eb0795063"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoTrader"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_LeftClick = m_UI.FindAction("LeftClick", throwIfNotFound: true);
        m_UI_MouseZoom = m_UI.FindAction("MouseZoom", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_OpenSettings = m_UI.FindAction("OpenSettings", throwIfNotFound: true);
        m_UI_CloseWindow = m_UI.FindAction("CloseWindow", throwIfNotFound: true);
        m_UI_DefenseBuildings = m_UI.FindAction("DefenseBuildings", throwIfNotFound: true);
        m_UI_IndustryBuildings = m_UI.FindAction("IndustryBuildings", throwIfNotFound: true);
        m_UI_PowerBuildings = m_UI.FindAction("PowerBuildings", throwIfNotFound: true);
        m_UI_PopulationBuildings = m_UI.FindAction("PopulationBuildings", throwIfNotFound: true);
        m_UI_CorporateBuildings = m_UI.FindAction("CorporateBuildings", throwIfNotFound: true);
        m_UI_TileMenu = m_UI.FindAction("TileMenu", throwIfNotFound: true);
        m_UI_MoveUnit = m_UI.FindAction("MoveUnit", throwIfNotFound: true);
        m_UI_OpenCheats = m_UI.FindAction("OpenCheats", throwIfNotFound: true);
        m_UI_AltPressed = m_UI.FindAction("AltPressed", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_NormalSpeed = m_UI.FindAction("NormalSpeed", throwIfNotFound: true);
        m_UI_DoubleSpeed = m_UI.FindAction("DoubleSpeed", throwIfNotFound: true);
        m_UI_TripleSpeed = m_UI.FindAction("TripleSpeed", throwIfNotFound: true);
        m_UI_TechTree = m_UI.FindAction("TechTree", throwIfNotFound: true);
        m_UI_Market = m_UI.FindAction("Market", throwIfNotFound: true);
        m_UI_AutoTrader = m_UI.FindAction("AutoTrader", throwIfNotFound: true);
        m_UI_HireMenu = m_UI.FindAction("HireMenu", throwIfNotFound: true);
        m_UI_Feedback = m_UI.FindAction("Feedback", throwIfNotFound: true);
        m_UI_SpaceLasers = m_UI.FindAction("SpaceLasers", throwIfNotFound: true);
        m_UI_Group1 = m_UI.FindAction("Group1", throwIfNotFound: true);
        m_UI_Group2 = m_UI.FindAction("Group2", throwIfNotFound: true);
        m_UI_Group3 = m_UI.FindAction("Group3", throwIfNotFound: true);
        m_UI_Group4 = m_UI.FindAction("Group4", throwIfNotFound: true);
        m_UI_Group5 = m_UI.FindAction("Group5", throwIfNotFound: true);
        m_UI_TabGroup = m_UI.FindAction("TabGroup", throwIfNotFound: true);
        m_UI_OpenLoad = m_UI.FindAction("OpenLoad", throwIfNotFound: true);
        m_UI_OpenSave = m_UI.FindAction("OpenSave", throwIfNotFound: true);
    }

    ~@UIControlActions()
    {
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, UIControlActions.UI.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_LeftClick;
    private readonly InputAction m_UI_MouseZoom;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_OpenSettings;
    private readonly InputAction m_UI_CloseWindow;
    private readonly InputAction m_UI_DefenseBuildings;
    private readonly InputAction m_UI_IndustryBuildings;
    private readonly InputAction m_UI_PowerBuildings;
    private readonly InputAction m_UI_PopulationBuildings;
    private readonly InputAction m_UI_CorporateBuildings;
    private readonly InputAction m_UI_TileMenu;
    private readonly InputAction m_UI_MoveUnit;
    private readonly InputAction m_UI_OpenCheats;
    private readonly InputAction m_UI_AltPressed;
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_NormalSpeed;
    private readonly InputAction m_UI_DoubleSpeed;
    private readonly InputAction m_UI_TripleSpeed;
    private readonly InputAction m_UI_TechTree;
    private readonly InputAction m_UI_Market;
    private readonly InputAction m_UI_AutoTrader;
    private readonly InputAction m_UI_HireMenu;
    private readonly InputAction m_UI_Feedback;
    private readonly InputAction m_UI_SpaceLasers;
    private readonly InputAction m_UI_Group1;
    private readonly InputAction m_UI_Group2;
    private readonly InputAction m_UI_Group3;
    private readonly InputAction m_UI_Group4;
    private readonly InputAction m_UI_Group5;
    private readonly InputAction m_UI_TabGroup;
    private readonly InputAction m_UI_OpenLoad;
    private readonly InputAction m_UI_OpenSave;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI".
    /// </summary>
    public struct UIActions
    {
        private @UIControlActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIActions(@UIControlActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI/LeftClick".
        /// </summary>
        public InputAction @LeftClick => m_Wrapper.m_UI_LeftClick;
        /// <summary>
        /// Provides access to the underlying input action "UI/MouseZoom".
        /// </summary>
        public InputAction @MouseZoom => m_Wrapper.m_UI_MouseZoom;
        /// <summary>
        /// Provides access to the underlying input action "UI/RightClick".
        /// </summary>
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        /// <summary>
        /// Provides access to the underlying input action "UI/OpenSettings".
        /// </summary>
        public InputAction @OpenSettings => m_Wrapper.m_UI_OpenSettings;
        /// <summary>
        /// Provides access to the underlying input action "UI/CloseWindow".
        /// </summary>
        public InputAction @CloseWindow => m_Wrapper.m_UI_CloseWindow;
        /// <summary>
        /// Provides access to the underlying input action "UI/DefenseBuildings".
        /// </summary>
        public InputAction @DefenseBuildings => m_Wrapper.m_UI_DefenseBuildings;
        /// <summary>
        /// Provides access to the underlying input action "UI/IndustryBuildings".
        /// </summary>
        public InputAction @IndustryBuildings => m_Wrapper.m_UI_IndustryBuildings;
        /// <summary>
        /// Provides access to the underlying input action "UI/PowerBuildings".
        /// </summary>
        public InputAction @PowerBuildings => m_Wrapper.m_UI_PowerBuildings;
        /// <summary>
        /// Provides access to the underlying input action "UI/PopulationBuildings".
        /// </summary>
        public InputAction @PopulationBuildings => m_Wrapper.m_UI_PopulationBuildings;
        /// <summary>
        /// Provides access to the underlying input action "UI/CorporateBuildings".
        /// </summary>
        public InputAction @CorporateBuildings => m_Wrapper.m_UI_CorporateBuildings;
        /// <summary>
        /// Provides access to the underlying input action "UI/TileMenu".
        /// </summary>
        public InputAction @TileMenu => m_Wrapper.m_UI_TileMenu;
        /// <summary>
        /// Provides access to the underlying input action "UI/MoveUnit".
        /// </summary>
        public InputAction @MoveUnit => m_Wrapper.m_UI_MoveUnit;
        /// <summary>
        /// Provides access to the underlying input action "UI/OpenCheats".
        /// </summary>
        public InputAction @OpenCheats => m_Wrapper.m_UI_OpenCheats;
        /// <summary>
        /// Provides access to the underlying input action "UI/AltPressed".
        /// </summary>
        public InputAction @AltPressed => m_Wrapper.m_UI_AltPressed;
        /// <summary>
        /// Provides access to the underlying input action "UI/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        /// <summary>
        /// Provides access to the underlying input action "UI/NormalSpeed".
        /// </summary>
        public InputAction @NormalSpeed => m_Wrapper.m_UI_NormalSpeed;
        /// <summary>
        /// Provides access to the underlying input action "UI/DoubleSpeed".
        /// </summary>
        public InputAction @DoubleSpeed => m_Wrapper.m_UI_DoubleSpeed;
        /// <summary>
        /// Provides access to the underlying input action "UI/TripleSpeed".
        /// </summary>
        public InputAction @TripleSpeed => m_Wrapper.m_UI_TripleSpeed;
        /// <summary>
        /// Provides access to the underlying input action "UI/TechTree".
        /// </summary>
        public InputAction @TechTree => m_Wrapper.m_UI_TechTree;
        /// <summary>
        /// Provides access to the underlying input action "UI/Market".
        /// </summary>
        public InputAction @Market => m_Wrapper.m_UI_Market;
        /// <summary>
        /// Provides access to the underlying input action "UI/AutoTrader".
        /// </summary>
        public InputAction @AutoTrader => m_Wrapper.m_UI_AutoTrader;
        /// <summary>
        /// Provides access to the underlying input action "UI/HireMenu".
        /// </summary>
        public InputAction @HireMenu => m_Wrapper.m_UI_HireMenu;
        /// <summary>
        /// Provides access to the underlying input action "UI/Feedback".
        /// </summary>
        public InputAction @Feedback => m_Wrapper.m_UI_Feedback;
        /// <summary>
        /// Provides access to the underlying input action "UI/SpaceLasers".
        /// </summary>
        public InputAction @SpaceLasers => m_Wrapper.m_UI_SpaceLasers;
        /// <summary>
        /// Provides access to the underlying input action "UI/Group1".
        /// </summary>
        public InputAction @Group1 => m_Wrapper.m_UI_Group1;
        /// <summary>
        /// Provides access to the underlying input action "UI/Group2".
        /// </summary>
        public InputAction @Group2 => m_Wrapper.m_UI_Group2;
        /// <summary>
        /// Provides access to the underlying input action "UI/Group3".
        /// </summary>
        public InputAction @Group3 => m_Wrapper.m_UI_Group3;
        /// <summary>
        /// Provides access to the underlying input action "UI/Group4".
        /// </summary>
        public InputAction @Group4 => m_Wrapper.m_UI_Group4;
        /// <summary>
        /// Provides access to the underlying input action "UI/Group5".
        /// </summary>
        public InputAction @Group5 => m_Wrapper.m_UI_Group5;
        /// <summary>
        /// Provides access to the underlying input action "UI/TabGroup".
        /// </summary>
        public InputAction @TabGroup => m_Wrapper.m_UI_TabGroup;
        /// <summary>
        /// Provides access to the underlying input action "UI/OpenLoad".
        /// </summary>
        public InputAction @OpenLoad => m_Wrapper.m_UI_OpenLoad;
        /// <summary>
        /// Provides access to the underlying input action "UI/OpenSave".
        /// </summary>
        public InputAction @OpenSave => m_Wrapper.m_UI_OpenSave;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIActions" />
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @MouseZoom.started += instance.OnMouseZoom;
            @MouseZoom.performed += instance.OnMouseZoom;
            @MouseZoom.canceled += instance.OnMouseZoom;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @OpenSettings.started += instance.OnOpenSettings;
            @OpenSettings.performed += instance.OnOpenSettings;
            @OpenSettings.canceled += instance.OnOpenSettings;
            @CloseWindow.started += instance.OnCloseWindow;
            @CloseWindow.performed += instance.OnCloseWindow;
            @CloseWindow.canceled += instance.OnCloseWindow;
            @DefenseBuildings.started += instance.OnDefenseBuildings;
            @DefenseBuildings.performed += instance.OnDefenseBuildings;
            @DefenseBuildings.canceled += instance.OnDefenseBuildings;
            @IndustryBuildings.started += instance.OnIndustryBuildings;
            @IndustryBuildings.performed += instance.OnIndustryBuildings;
            @IndustryBuildings.canceled += instance.OnIndustryBuildings;
            @PowerBuildings.started += instance.OnPowerBuildings;
            @PowerBuildings.performed += instance.OnPowerBuildings;
            @PowerBuildings.canceled += instance.OnPowerBuildings;
            @PopulationBuildings.started += instance.OnPopulationBuildings;
            @PopulationBuildings.performed += instance.OnPopulationBuildings;
            @PopulationBuildings.canceled += instance.OnPopulationBuildings;
            @CorporateBuildings.started += instance.OnCorporateBuildings;
            @CorporateBuildings.performed += instance.OnCorporateBuildings;
            @CorporateBuildings.canceled += instance.OnCorporateBuildings;
            @TileMenu.started += instance.OnTileMenu;
            @TileMenu.performed += instance.OnTileMenu;
            @TileMenu.canceled += instance.OnTileMenu;
            @MoveUnit.started += instance.OnMoveUnit;
            @MoveUnit.performed += instance.OnMoveUnit;
            @MoveUnit.canceled += instance.OnMoveUnit;
            @OpenCheats.started += instance.OnOpenCheats;
            @OpenCheats.performed += instance.OnOpenCheats;
            @OpenCheats.canceled += instance.OnOpenCheats;
            @AltPressed.started += instance.OnAltPressed;
            @AltPressed.performed += instance.OnAltPressed;
            @AltPressed.canceled += instance.OnAltPressed;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @NormalSpeed.started += instance.OnNormalSpeed;
            @NormalSpeed.performed += instance.OnNormalSpeed;
            @NormalSpeed.canceled += instance.OnNormalSpeed;
            @DoubleSpeed.started += instance.OnDoubleSpeed;
            @DoubleSpeed.performed += instance.OnDoubleSpeed;
            @DoubleSpeed.canceled += instance.OnDoubleSpeed;
            @TripleSpeed.started += instance.OnTripleSpeed;
            @TripleSpeed.performed += instance.OnTripleSpeed;
            @TripleSpeed.canceled += instance.OnTripleSpeed;
            @TechTree.started += instance.OnTechTree;
            @TechTree.performed += instance.OnTechTree;
            @TechTree.canceled += instance.OnTechTree;
            @Market.started += instance.OnMarket;
            @Market.performed += instance.OnMarket;
            @Market.canceled += instance.OnMarket;
            @AutoTrader.started += instance.OnAutoTrader;
            @AutoTrader.performed += instance.OnAutoTrader;
            @AutoTrader.canceled += instance.OnAutoTrader;
            @HireMenu.started += instance.OnHireMenu;
            @HireMenu.performed += instance.OnHireMenu;
            @HireMenu.canceled += instance.OnHireMenu;
            @Feedback.started += instance.OnFeedback;
            @Feedback.performed += instance.OnFeedback;
            @Feedback.canceled += instance.OnFeedback;
            @SpaceLasers.started += instance.OnSpaceLasers;
            @SpaceLasers.performed += instance.OnSpaceLasers;
            @SpaceLasers.canceled += instance.OnSpaceLasers;
            @Group1.started += instance.OnGroup1;
            @Group1.performed += instance.OnGroup1;
            @Group1.canceled += instance.OnGroup1;
            @Group2.started += instance.OnGroup2;
            @Group2.performed += instance.OnGroup2;
            @Group2.canceled += instance.OnGroup2;
            @Group3.started += instance.OnGroup3;
            @Group3.performed += instance.OnGroup3;
            @Group3.canceled += instance.OnGroup3;
            @Group4.started += instance.OnGroup4;
            @Group4.performed += instance.OnGroup4;
            @Group4.canceled += instance.OnGroup4;
            @Group5.started += instance.OnGroup5;
            @Group5.performed += instance.OnGroup5;
            @Group5.canceled += instance.OnGroup5;
            @TabGroup.started += instance.OnTabGroup;
            @TabGroup.performed += instance.OnTabGroup;
            @TabGroup.canceled += instance.OnTabGroup;
            @OpenLoad.started += instance.OnOpenLoad;
            @OpenLoad.performed += instance.OnOpenLoad;
            @OpenLoad.canceled += instance.OnOpenLoad;
            @OpenSave.started += instance.OnOpenSave;
            @OpenSave.performed += instance.OnOpenSave;
            @OpenSave.canceled += instance.OnOpenSave;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIActions" />
        private void UnregisterCallbacks(IUIActions instance)
        {
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @MouseZoom.started -= instance.OnMouseZoom;
            @MouseZoom.performed -= instance.OnMouseZoom;
            @MouseZoom.canceled -= instance.OnMouseZoom;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @OpenSettings.started -= instance.OnOpenSettings;
            @OpenSettings.performed -= instance.OnOpenSettings;
            @OpenSettings.canceled -= instance.OnOpenSettings;
            @CloseWindow.started -= instance.OnCloseWindow;
            @CloseWindow.performed -= instance.OnCloseWindow;
            @CloseWindow.canceled -= instance.OnCloseWindow;
            @DefenseBuildings.started -= instance.OnDefenseBuildings;
            @DefenseBuildings.performed -= instance.OnDefenseBuildings;
            @DefenseBuildings.canceled -= instance.OnDefenseBuildings;
            @IndustryBuildings.started -= instance.OnIndustryBuildings;
            @IndustryBuildings.performed -= instance.OnIndustryBuildings;
            @IndustryBuildings.canceled -= instance.OnIndustryBuildings;
            @PowerBuildings.started -= instance.OnPowerBuildings;
            @PowerBuildings.performed -= instance.OnPowerBuildings;
            @PowerBuildings.canceled -= instance.OnPowerBuildings;
            @PopulationBuildings.started -= instance.OnPopulationBuildings;
            @PopulationBuildings.performed -= instance.OnPopulationBuildings;
            @PopulationBuildings.canceled -= instance.OnPopulationBuildings;
            @CorporateBuildings.started -= instance.OnCorporateBuildings;
            @CorporateBuildings.performed -= instance.OnCorporateBuildings;
            @CorporateBuildings.canceled -= instance.OnCorporateBuildings;
            @TileMenu.started -= instance.OnTileMenu;
            @TileMenu.performed -= instance.OnTileMenu;
            @TileMenu.canceled -= instance.OnTileMenu;
            @MoveUnit.started -= instance.OnMoveUnit;
            @MoveUnit.performed -= instance.OnMoveUnit;
            @MoveUnit.canceled -= instance.OnMoveUnit;
            @OpenCheats.started -= instance.OnOpenCheats;
            @OpenCheats.performed -= instance.OnOpenCheats;
            @OpenCheats.canceled -= instance.OnOpenCheats;
            @AltPressed.started -= instance.OnAltPressed;
            @AltPressed.performed -= instance.OnAltPressed;
            @AltPressed.canceled -= instance.OnAltPressed;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @NormalSpeed.started -= instance.OnNormalSpeed;
            @NormalSpeed.performed -= instance.OnNormalSpeed;
            @NormalSpeed.canceled -= instance.OnNormalSpeed;
            @DoubleSpeed.started -= instance.OnDoubleSpeed;
            @DoubleSpeed.performed -= instance.OnDoubleSpeed;
            @DoubleSpeed.canceled -= instance.OnDoubleSpeed;
            @TripleSpeed.started -= instance.OnTripleSpeed;
            @TripleSpeed.performed -= instance.OnTripleSpeed;
            @TripleSpeed.canceled -= instance.OnTripleSpeed;
            @TechTree.started -= instance.OnTechTree;
            @TechTree.performed -= instance.OnTechTree;
            @TechTree.canceled -= instance.OnTechTree;
            @Market.started -= instance.OnMarket;
            @Market.performed -= instance.OnMarket;
            @Market.canceled -= instance.OnMarket;
            @AutoTrader.started -= instance.OnAutoTrader;
            @AutoTrader.performed -= instance.OnAutoTrader;
            @AutoTrader.canceled -= instance.OnAutoTrader;
            @HireMenu.started -= instance.OnHireMenu;
            @HireMenu.performed -= instance.OnHireMenu;
            @HireMenu.canceled -= instance.OnHireMenu;
            @Feedback.started -= instance.OnFeedback;
            @Feedback.performed -= instance.OnFeedback;
            @Feedback.canceled -= instance.OnFeedback;
            @SpaceLasers.started -= instance.OnSpaceLasers;
            @SpaceLasers.performed -= instance.OnSpaceLasers;
            @SpaceLasers.canceled -= instance.OnSpaceLasers;
            @Group1.started -= instance.OnGroup1;
            @Group1.performed -= instance.OnGroup1;
            @Group1.canceled -= instance.OnGroup1;
            @Group2.started -= instance.OnGroup2;
            @Group2.performed -= instance.OnGroup2;
            @Group2.canceled -= instance.OnGroup2;
            @Group3.started -= instance.OnGroup3;
            @Group3.performed -= instance.OnGroup3;
            @Group3.canceled -= instance.OnGroup3;
            @Group4.started -= instance.OnGroup4;
            @Group4.performed -= instance.OnGroup4;
            @Group4.canceled -= instance.OnGroup4;
            @Group5.started -= instance.OnGroup5;
            @Group5.performed -= instance.OnGroup5;
            @Group5.canceled -= instance.OnGroup5;
            @TabGroup.started -= instance.OnTabGroup;
            @TabGroup.performed -= instance.OnTabGroup;
            @TabGroup.canceled -= instance.OnTabGroup;
            @OpenLoad.started -= instance.OnOpenLoad;
            @OpenLoad.performed -= instance.OnOpenLoad;
            @OpenLoad.canceled -= instance.OnOpenLoad;
            @OpenSave.started -= instance.OnOpenSave;
            @OpenSave.performed -= instance.OnOpenSave;
            @OpenSave.canceled -= instance.OnOpenSave;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIActions.UnregisterCallbacks(IUIActions)" />.
        /// </summary>
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIActions" /> instance referencing this action map.
    /// </summary>
    public UIActions @UI => new UIActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
    /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
    public interface IUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MouseZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseZoom(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenSettings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenSettings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CloseWindow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCloseWindow(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DefenseBuildings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDefenseBuildings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IndustryBuildings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIndustryBuildings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PowerBuildings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPowerBuildings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PopulationBuildings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPopulationBuildings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CorporateBuildings" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCorporateBuildings(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TileMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTileMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveUnit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveUnit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenCheats" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenCheats(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AltPressed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAltPressed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NormalSpeed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNormalSpeed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DoubleSpeed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDoubleSpeed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TripleSpeed" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTripleSpeed(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TechTree" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTechTree(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Market" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMarket(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AutoTrader" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAutoTrader(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "HireMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHireMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Feedback" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFeedback(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpaceLasers" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpaceLasers(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Group1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGroup1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Group2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGroup2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Group3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGroup3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Group4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGroup4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Group5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGroup5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TabGroup" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTabGroup(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenLoad" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenLoad(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenSave" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenSave(InputAction.CallbackContext context);
    }
}
