//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input Settings/UIControlActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIControlActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIControlActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIControlActions"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""147ec46a-df48-4a13-80ec-062dd1fd2a9a"",
            ""actions"": [
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""db5f52c4-8916-4ce3-87a6-857ee71d15a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""b382e10c-648a-42fe-99e1-a383f08974a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSettings"",
                    ""type"": ""Button"",
                    ""id"": ""7edd42f4-6c3c-4eb4-9116-2311633dc938"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseWindow"",
                    ""type"": ""Button"",
                    ""id"": ""76194f25-8a56-457d-9cb8-796bf3ff4657"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DefenseBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""3125c5bb-bc84-43a0-9706-0a745b619b4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IndustryBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""cdc85c29-d927-4267-b262-fa85e92c8d2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PowerBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""578996e3-90f0-4953-bfcc-f303c2894fbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PopulationBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""0ce1deb0-d2a3-4d7e-a21e-b0636b622c78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CorporateBuildings"",
                    ""type"": ""Button"",
                    ""id"": ""636eb401-48f4-4231-b9fd-bbf6dbc35f66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TileMenu"",
                    ""type"": ""Button"",
                    ""id"": ""ccab643f-ec44-49a2-9cd9-42dd535d5ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUnit"",
                    ""type"": ""Button"",
                    ""id"": ""f68e5075-45be-4458-98af-c57922f4b9ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCheats"",
                    ""type"": ""Button"",
                    ""id"": ""53eb4c35-6205-4fa7-9903-fc0476f9688c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltPressed"",
                    ""type"": ""Button"",
                    ""id"": ""2dedd837-cc18-4270-b6f4-011f4d14f95a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""22e7730a-6504-45f6-b8c0-0bce3e270593"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NormalSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""14a0ace3-a0dd-45ea-ae91-d639feff17ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""6485f01b-6bc4-4623-84b8-f68c83c50d12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TripleSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""51a0fc16-712b-46b0-8c97-867af172ef53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TechTree"",
                    ""type"": ""Button"",
                    ""id"": ""7b844b46-9ec8-4c4e-a855-70385ccf7ce0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StockMarket"",
                    ""type"": ""Button"",
                    ""id"": ""282d0550-8ec6-4c4f-afab-27e3281b9da2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HireMenu"",
                    ""type"": ""Button"",
                    ""id"": ""1b8a0534-e99e-400d-ab96-e45ad708d322"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Feedback"",
                    ""type"": ""Button"",
                    ""id"": ""2419eab5-7e3a-4cc9-b2fa-4cc43db4b541"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceLasers"",
                    ""type"": ""Button"",
                    ""id"": ""3e229d39-650e-41b9-b704-ccfe8ab0bc8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group1"",
                    ""type"": ""Button"",
                    ""id"": ""8d605fe5-deb5-4c2b-a70e-ff3aedd3472c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group2"",
                    ""type"": ""Button"",
                    ""id"": ""dab28750-b076-486a-9c95-3e98b9974059"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group3"",
                    ""type"": ""Button"",
                    ""id"": ""b3beafcc-3fb3-4a4b-9197-e5eb501edf2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group4"",
                    ""type"": ""Button"",
                    ""id"": ""c4cec9a8-b1e9-4abf-8555-debb450be2a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Group5"",
                    ""type"": ""Button"",
                    ""id"": ""8893827d-1123-496e-93ea-ea272e57cf0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabGroup"",
                    ""type"": ""Button"",
                    ""id"": ""a714751c-9039-480f-b640-ea74a83b89e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""53b4fd35-51d3-499c-8692-7a52d046a359"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DefenseBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""134cac0a-29b4-4522-821c-abdd5197dc94"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IndustryBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""105cca7a-5e03-4c9f-934e-78366b55e034"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PowerBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc08b468-97ea-4927-ac37-c97967da86c7"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PopulationBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e24a7c01-e1d9-46c8-85c3-498248347c22"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CorporateBuildings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56d8ea2-5e6a-454e-8016-4dc0048b28fb"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TileMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0377cc2e-1a4d-4763-a7d6-7eadaf5b0185"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90b887c7-cb7b-4786-94f9-8868292f26fa"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b6c1d5e-1cc3-49f7-9907-9cf5f995d4a5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1992e84-3ad4-4b33-924b-0c3d5f457f3f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e66a906c-8f47-44bf-9b42-299558ba7a29"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""a2f02bd5-2778-42da-910c-6d4c2355e67a"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""ab91c920-b077-4ddd-8bfc-ff31a7405431"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""ffb0e9bb-dce4-4e9d-ae07-1b071636c7b8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5b508e99-e484-466e-a1dd-2e0e3b1b19d5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""33528b52-458d-4946-aa57-c45b5b1fc0b6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04f45881-02c1-4474-8b48-4e4fa018a9e0"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b48837ac-92c5-4918-8ed9-b7dd9764f271"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0fcf5e1-4c23-4557-a547-71015ca3dd01"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoubleSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f38ec7ed-6964-4218-a289-99218f5d9d2f"",
                    ""path"": ""<Keyboard>/backslash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TripleSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44d9cdb1-de87-44d1-8c46-5c0f3e595fe0"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TechTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b08cce15-d8ce-48c2-ae2f-855d1d762b57"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StockMarket"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99dfdcb8-06ed-48e5-a882-8f10b153fba4"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HireMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""728fe859-ade9-4644-a348-60daf48c0185"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Feedback"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4271eb22-e06c-4a35-a897-53875827403d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceLasers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f26fbdf7-fc00-4c94-9777-13660a4b8f95"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ac0e9a6-44bd-4f80-90a6-cabdfa3ba33a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47506cb8-d18d-4ddf-8afb-1617872fe8d3"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34fa6486-b556-4a56-b2ff-56b9a858f30f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fab71d4f-9594-4be4-8c26-1f80f6d740c6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Group5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e7c8fcf-2cf0-4a70-ad32-4fb338d6bf6e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabGroup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_LeftClick = m_UI.FindAction("LeftClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_OpenSettings = m_UI.FindAction("OpenSettings", throwIfNotFound: true);
        m_UI_CloseWindow = m_UI.FindAction("CloseWindow", throwIfNotFound: true);
        m_UI_DefenseBuildings = m_UI.FindAction("DefenseBuildings", throwIfNotFound: true);
        m_UI_IndustryBuildings = m_UI.FindAction("IndustryBuildings", throwIfNotFound: true);
        m_UI_PowerBuildings = m_UI.FindAction("PowerBuildings", throwIfNotFound: true);
        m_UI_PopulationBuildings = m_UI.FindAction("PopulationBuildings", throwIfNotFound: true);
        m_UI_CorporateBuildings = m_UI.FindAction("CorporateBuildings", throwIfNotFound: true);
        m_UI_TileMenu = m_UI.FindAction("TileMenu", throwIfNotFound: true);
        m_UI_MoveUnit = m_UI.FindAction("MoveUnit", throwIfNotFound: true);
        m_UI_OpenCheats = m_UI.FindAction("OpenCheats", throwIfNotFound: true);
        m_UI_AltPressed = m_UI.FindAction("AltPressed", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_NormalSpeed = m_UI.FindAction("NormalSpeed", throwIfNotFound: true);
        m_UI_DoubleSpeed = m_UI.FindAction("DoubleSpeed", throwIfNotFound: true);
        m_UI_TripleSpeed = m_UI.FindAction("TripleSpeed", throwIfNotFound: true);
        m_UI_TechTree = m_UI.FindAction("TechTree", throwIfNotFound: true);
        m_UI_StockMarket = m_UI.FindAction("StockMarket", throwIfNotFound: true);
        m_UI_HireMenu = m_UI.FindAction("HireMenu", throwIfNotFound: true);
        m_UI_Feedback = m_UI.FindAction("Feedback", throwIfNotFound: true);
        m_UI_SpaceLasers = m_UI.FindAction("SpaceLasers", throwIfNotFound: true);
        m_UI_Group1 = m_UI.FindAction("Group1", throwIfNotFound: true);
        m_UI_Group2 = m_UI.FindAction("Group2", throwIfNotFound: true);
        m_UI_Group3 = m_UI.FindAction("Group3", throwIfNotFound: true);
        m_UI_Group4 = m_UI.FindAction("Group4", throwIfNotFound: true);
        m_UI_Group5 = m_UI.FindAction("Group5", throwIfNotFound: true);
        m_UI_TabGroup = m_UI.FindAction("TabGroup", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_LeftClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_OpenSettings;
    private readonly InputAction m_UI_CloseWindow;
    private readonly InputAction m_UI_DefenseBuildings;
    private readonly InputAction m_UI_IndustryBuildings;
    private readonly InputAction m_UI_PowerBuildings;
    private readonly InputAction m_UI_PopulationBuildings;
    private readonly InputAction m_UI_CorporateBuildings;
    private readonly InputAction m_UI_TileMenu;
    private readonly InputAction m_UI_MoveUnit;
    private readonly InputAction m_UI_OpenCheats;
    private readonly InputAction m_UI_AltPressed;
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_NormalSpeed;
    private readonly InputAction m_UI_DoubleSpeed;
    private readonly InputAction m_UI_TripleSpeed;
    private readonly InputAction m_UI_TechTree;
    private readonly InputAction m_UI_StockMarket;
    private readonly InputAction m_UI_HireMenu;
    private readonly InputAction m_UI_Feedback;
    private readonly InputAction m_UI_SpaceLasers;
    private readonly InputAction m_UI_Group1;
    private readonly InputAction m_UI_Group2;
    private readonly InputAction m_UI_Group3;
    private readonly InputAction m_UI_Group4;
    private readonly InputAction m_UI_Group5;
    private readonly InputAction m_UI_TabGroup;
    public struct UIActions
    {
        private @UIControlActions m_Wrapper;
        public UIActions(@UIControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftClick => m_Wrapper.m_UI_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @OpenSettings => m_Wrapper.m_UI_OpenSettings;
        public InputAction @CloseWindow => m_Wrapper.m_UI_CloseWindow;
        public InputAction @DefenseBuildings => m_Wrapper.m_UI_DefenseBuildings;
        public InputAction @IndustryBuildings => m_Wrapper.m_UI_IndustryBuildings;
        public InputAction @PowerBuildings => m_Wrapper.m_UI_PowerBuildings;
        public InputAction @PopulationBuildings => m_Wrapper.m_UI_PopulationBuildings;
        public InputAction @CorporateBuildings => m_Wrapper.m_UI_CorporateBuildings;
        public InputAction @TileMenu => m_Wrapper.m_UI_TileMenu;
        public InputAction @MoveUnit => m_Wrapper.m_UI_MoveUnit;
        public InputAction @OpenCheats => m_Wrapper.m_UI_OpenCheats;
        public InputAction @AltPressed => m_Wrapper.m_UI_AltPressed;
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputAction @NormalSpeed => m_Wrapper.m_UI_NormalSpeed;
        public InputAction @DoubleSpeed => m_Wrapper.m_UI_DoubleSpeed;
        public InputAction @TripleSpeed => m_Wrapper.m_UI_TripleSpeed;
        public InputAction @TechTree => m_Wrapper.m_UI_TechTree;
        public InputAction @StockMarket => m_Wrapper.m_UI_StockMarket;
        public InputAction @HireMenu => m_Wrapper.m_UI_HireMenu;
        public InputAction @Feedback => m_Wrapper.m_UI_Feedback;
        public InputAction @SpaceLasers => m_Wrapper.m_UI_SpaceLasers;
        public InputAction @Group1 => m_Wrapper.m_UI_Group1;
        public InputAction @Group2 => m_Wrapper.m_UI_Group2;
        public InputAction @Group3 => m_Wrapper.m_UI_Group3;
        public InputAction @Group4 => m_Wrapper.m_UI_Group4;
        public InputAction @Group5 => m_Wrapper.m_UI_Group5;
        public InputAction @TabGroup => m_Wrapper.m_UI_TabGroup;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @OpenSettings.started += instance.OnOpenSettings;
            @OpenSettings.performed += instance.OnOpenSettings;
            @OpenSettings.canceled += instance.OnOpenSettings;
            @CloseWindow.started += instance.OnCloseWindow;
            @CloseWindow.performed += instance.OnCloseWindow;
            @CloseWindow.canceled += instance.OnCloseWindow;
            @DefenseBuildings.started += instance.OnDefenseBuildings;
            @DefenseBuildings.performed += instance.OnDefenseBuildings;
            @DefenseBuildings.canceled += instance.OnDefenseBuildings;
            @IndustryBuildings.started += instance.OnIndustryBuildings;
            @IndustryBuildings.performed += instance.OnIndustryBuildings;
            @IndustryBuildings.canceled += instance.OnIndustryBuildings;
            @PowerBuildings.started += instance.OnPowerBuildings;
            @PowerBuildings.performed += instance.OnPowerBuildings;
            @PowerBuildings.canceled += instance.OnPowerBuildings;
            @PopulationBuildings.started += instance.OnPopulationBuildings;
            @PopulationBuildings.performed += instance.OnPopulationBuildings;
            @PopulationBuildings.canceled += instance.OnPopulationBuildings;
            @CorporateBuildings.started += instance.OnCorporateBuildings;
            @CorporateBuildings.performed += instance.OnCorporateBuildings;
            @CorporateBuildings.canceled += instance.OnCorporateBuildings;
            @TileMenu.started += instance.OnTileMenu;
            @TileMenu.performed += instance.OnTileMenu;
            @TileMenu.canceled += instance.OnTileMenu;
            @MoveUnit.started += instance.OnMoveUnit;
            @MoveUnit.performed += instance.OnMoveUnit;
            @MoveUnit.canceled += instance.OnMoveUnit;
            @OpenCheats.started += instance.OnOpenCheats;
            @OpenCheats.performed += instance.OnOpenCheats;
            @OpenCheats.canceled += instance.OnOpenCheats;
            @AltPressed.started += instance.OnAltPressed;
            @AltPressed.performed += instance.OnAltPressed;
            @AltPressed.canceled += instance.OnAltPressed;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @NormalSpeed.started += instance.OnNormalSpeed;
            @NormalSpeed.performed += instance.OnNormalSpeed;
            @NormalSpeed.canceled += instance.OnNormalSpeed;
            @DoubleSpeed.started += instance.OnDoubleSpeed;
            @DoubleSpeed.performed += instance.OnDoubleSpeed;
            @DoubleSpeed.canceled += instance.OnDoubleSpeed;
            @TripleSpeed.started += instance.OnTripleSpeed;
            @TripleSpeed.performed += instance.OnTripleSpeed;
            @TripleSpeed.canceled += instance.OnTripleSpeed;
            @TechTree.started += instance.OnTechTree;
            @TechTree.performed += instance.OnTechTree;
            @TechTree.canceled += instance.OnTechTree;
            @StockMarket.started += instance.OnStockMarket;
            @StockMarket.performed += instance.OnStockMarket;
            @StockMarket.canceled += instance.OnStockMarket;
            @HireMenu.started += instance.OnHireMenu;
            @HireMenu.performed += instance.OnHireMenu;
            @HireMenu.canceled += instance.OnHireMenu;
            @Feedback.started += instance.OnFeedback;
            @Feedback.performed += instance.OnFeedback;
            @Feedback.canceled += instance.OnFeedback;
            @SpaceLasers.started += instance.OnSpaceLasers;
            @SpaceLasers.performed += instance.OnSpaceLasers;
            @SpaceLasers.canceled += instance.OnSpaceLasers;
            @Group1.started += instance.OnGroup1;
            @Group1.performed += instance.OnGroup1;
            @Group1.canceled += instance.OnGroup1;
            @Group2.started += instance.OnGroup2;
            @Group2.performed += instance.OnGroup2;
            @Group2.canceled += instance.OnGroup2;
            @Group3.started += instance.OnGroup3;
            @Group3.performed += instance.OnGroup3;
            @Group3.canceled += instance.OnGroup3;
            @Group4.started += instance.OnGroup4;
            @Group4.performed += instance.OnGroup4;
            @Group4.canceled += instance.OnGroup4;
            @Group5.started += instance.OnGroup5;
            @Group5.performed += instance.OnGroup5;
            @Group5.canceled += instance.OnGroup5;
            @TabGroup.started += instance.OnTabGroup;
            @TabGroup.performed += instance.OnTabGroup;
            @TabGroup.canceled += instance.OnTabGroup;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @OpenSettings.started -= instance.OnOpenSettings;
            @OpenSettings.performed -= instance.OnOpenSettings;
            @OpenSettings.canceled -= instance.OnOpenSettings;
            @CloseWindow.started -= instance.OnCloseWindow;
            @CloseWindow.performed -= instance.OnCloseWindow;
            @CloseWindow.canceled -= instance.OnCloseWindow;
            @DefenseBuildings.started -= instance.OnDefenseBuildings;
            @DefenseBuildings.performed -= instance.OnDefenseBuildings;
            @DefenseBuildings.canceled -= instance.OnDefenseBuildings;
            @IndustryBuildings.started -= instance.OnIndustryBuildings;
            @IndustryBuildings.performed -= instance.OnIndustryBuildings;
            @IndustryBuildings.canceled -= instance.OnIndustryBuildings;
            @PowerBuildings.started -= instance.OnPowerBuildings;
            @PowerBuildings.performed -= instance.OnPowerBuildings;
            @PowerBuildings.canceled -= instance.OnPowerBuildings;
            @PopulationBuildings.started -= instance.OnPopulationBuildings;
            @PopulationBuildings.performed -= instance.OnPopulationBuildings;
            @PopulationBuildings.canceled -= instance.OnPopulationBuildings;
            @CorporateBuildings.started -= instance.OnCorporateBuildings;
            @CorporateBuildings.performed -= instance.OnCorporateBuildings;
            @CorporateBuildings.canceled -= instance.OnCorporateBuildings;
            @TileMenu.started -= instance.OnTileMenu;
            @TileMenu.performed -= instance.OnTileMenu;
            @TileMenu.canceled -= instance.OnTileMenu;
            @MoveUnit.started -= instance.OnMoveUnit;
            @MoveUnit.performed -= instance.OnMoveUnit;
            @MoveUnit.canceled -= instance.OnMoveUnit;
            @OpenCheats.started -= instance.OnOpenCheats;
            @OpenCheats.performed -= instance.OnOpenCheats;
            @OpenCheats.canceled -= instance.OnOpenCheats;
            @AltPressed.started -= instance.OnAltPressed;
            @AltPressed.performed -= instance.OnAltPressed;
            @AltPressed.canceled -= instance.OnAltPressed;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @NormalSpeed.started -= instance.OnNormalSpeed;
            @NormalSpeed.performed -= instance.OnNormalSpeed;
            @NormalSpeed.canceled -= instance.OnNormalSpeed;
            @DoubleSpeed.started -= instance.OnDoubleSpeed;
            @DoubleSpeed.performed -= instance.OnDoubleSpeed;
            @DoubleSpeed.canceled -= instance.OnDoubleSpeed;
            @TripleSpeed.started -= instance.OnTripleSpeed;
            @TripleSpeed.performed -= instance.OnTripleSpeed;
            @TripleSpeed.canceled -= instance.OnTripleSpeed;
            @TechTree.started -= instance.OnTechTree;
            @TechTree.performed -= instance.OnTechTree;
            @TechTree.canceled -= instance.OnTechTree;
            @StockMarket.started -= instance.OnStockMarket;
            @StockMarket.performed -= instance.OnStockMarket;
            @StockMarket.canceled -= instance.OnStockMarket;
            @HireMenu.started -= instance.OnHireMenu;
            @HireMenu.performed -= instance.OnHireMenu;
            @HireMenu.canceled -= instance.OnHireMenu;
            @Feedback.started -= instance.OnFeedback;
            @Feedback.performed -= instance.OnFeedback;
            @Feedback.canceled -= instance.OnFeedback;
            @SpaceLasers.started -= instance.OnSpaceLasers;
            @SpaceLasers.performed -= instance.OnSpaceLasers;
            @SpaceLasers.canceled -= instance.OnSpaceLasers;
            @Group1.started -= instance.OnGroup1;
            @Group1.performed -= instance.OnGroup1;
            @Group1.canceled -= instance.OnGroup1;
            @Group2.started -= instance.OnGroup2;
            @Group2.performed -= instance.OnGroup2;
            @Group2.canceled -= instance.OnGroup2;
            @Group3.started -= instance.OnGroup3;
            @Group3.performed -= instance.OnGroup3;
            @Group3.canceled -= instance.OnGroup3;
            @Group4.started -= instance.OnGroup4;
            @Group4.performed -= instance.OnGroup4;
            @Group4.canceled -= instance.OnGroup4;
            @Group5.started -= instance.OnGroup5;
            @Group5.performed -= instance.OnGroup5;
            @Group5.canceled -= instance.OnGroup5;
            @TabGroup.started -= instance.OnTabGroup;
            @TabGroup.performed -= instance.OnTabGroup;
            @TabGroup.canceled -= instance.OnTabGroup;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IUIActions
    {
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnOpenSettings(InputAction.CallbackContext context);
        void OnCloseWindow(InputAction.CallbackContext context);
        void OnDefenseBuildings(InputAction.CallbackContext context);
        void OnIndustryBuildings(InputAction.CallbackContext context);
        void OnPowerBuildings(InputAction.CallbackContext context);
        void OnPopulationBuildings(InputAction.CallbackContext context);
        void OnCorporateBuildings(InputAction.CallbackContext context);
        void OnTileMenu(InputAction.CallbackContext context);
        void OnMoveUnit(InputAction.CallbackContext context);
        void OnOpenCheats(InputAction.CallbackContext context);
        void OnAltPressed(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnNormalSpeed(InputAction.CallbackContext context);
        void OnDoubleSpeed(InputAction.CallbackContext context);
        void OnTripleSpeed(InputAction.CallbackContext context);
        void OnTechTree(InputAction.CallbackContext context);
        void OnStockMarket(InputAction.CallbackContext context);
        void OnHireMenu(InputAction.CallbackContext context);
        void OnFeedback(InputAction.CallbackContext context);
        void OnSpaceLasers(InputAction.CallbackContext context);
        void OnGroup1(InputAction.CallbackContext context);
        void OnGroup2(InputAction.CallbackContext context);
        void OnGroup3(InputAction.CallbackContext context);
        void OnGroup4(InputAction.CallbackContext context);
        void OnGroup5(InputAction.CallbackContext context);
        void OnTabGroup(InputAction.CallbackContext context);
    }
}
